root: true
env:
  es2020: true
  node: true
  jest/globals: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
  ecmaVersion: 2020,
plugins:
  - jest
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jest/recommended"
  - "prettier"
